stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: tahmasbi/myrepo
  KUBE_CONFIG: /root/.kube/config
build:
  stage: build
  image: docker
  script:
    - echo "Build Docker image with 2 tags..."
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA -t $IMAGE_NAME:latest .
    - echo "Push Docker image with commit tag..."
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - echo "Push Docker image with latest tag..."
    - docker push $IMAGE_NAME:latest
  only:
    - dev
    - merge_requests
    - tags

test:
  stage: test
  image: docker.arvancloud.ir/python:3.12-slim
  script:
    - echo "RUN ..."
    - python -c "from app import main; main()"

deploy:
  stage: deploy
  image: docker.arvancloud.ir/lachlanevenson/k8s-kubectl:v1.32.0
  script:
    - kubectl apply -f deployment.yaml
    - kubectl rollout status deployment/my-app
  only:
    - dev
    - tags
