stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: tahmasbi/myrepo
build:
  stage: build
  image: docker
  script:
    - echo "Login To Docker Hub..."
    - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS"
    - echo "Build Docker image with 2 tags..."
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA -t $IMAGE_NAME:latest .
    - echo "Push Docker image with commit tag..."
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - echo "Push Docker image with latest tag..."
    - docker push $IMAGE_NAME:latest
  only:
    - dev
    - merge_requests
    - tags

test:
  stage: test
  image: docker.arvancloud.ir/python:3.12-slim
  script:
    - echo "RUN ..."
    - python -c "from app import main; main()"

deploy:
  stage: deploy
  image: docker.arvancloud.ir/dtzar/helm-kubectl:3.18
  script:
    - mkdir -p ~/.kube
    - chmod 700 ~/.kube
    - echo "$KUBE_CONFIG" > ~/.kube/config
    - sed -i "s/latest/$CI_PIPELINE_ID/g" deployment.yaml
    - kubectl apply -f deployment.yaml
  only:
    - dev
    - tags


