stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: tahmasbi/myrepo
  KUBE_CONFIG: /root/.kube/config
build:
  stage: build
  image: docker
  script:
    - echo "Login To Docker Hub..."
    - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS"
    - echo "Build Docker image..."
    - docker build -t $IMAGE_NAME .
    - echo "Send Docker image to Docker Hub..."
    - docker push $IMAGE_NAME
  rules:
    - if: $CI_COMMIT_BRANCH

test:
  stage: test
  image: docker.arvancloud.ir/python:3.12-slim
  script:
    - echo "RUN ..."
    - python -c "from app import main; main()"
  rules:
    - if: $CI_COMMIT_BRANCH

deploy:
  stage: deploy
  image: docker.arvancloud.ir/bitnami/kubectl:latest
  script:
    - echo "Deploying..."
    - kubectl --kubeconfig=$KUBE_CONFIG set image deployment/my-app my-app=$IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - kubectl --kubeconfig=$KUBE_CONFIG rollout status deployment/my-app
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - if: '$CI_COMMIT_TAG'
      when: manual
