stages:
  - build
  - dev
  - test

variables:
  IMAGE_NAME: tahmasbi/myrepo

build:
  stage: build
  image: docker
  script:
    - echo "Login To Docker Hub..."
    - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
    - echo "Build Docker image..."
    - docker build -t $IMAGE_NAME .
    - echo "Send Docker image to Docker Hub..."
    - docker push $IMAGE_NAME

dev:
  stage: dev
  image: docker:24.0.2
  services:
    - name: docker:24-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Run Container in dev..."
    - docker run --rm $IMAGE_NAME

test:
  stage: test
  image: python:3.12-slim
  script:
    - echo "RUN ..."
    - python -c "from app import main; main()"

